networks:
  dev:

services:
  db:
    image: postgres:16.2
    container_name: tasktracker_db
    restart: always
    shm_size: 128mb
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: tracker
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d tracker"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - dev

#  nginx:
#    image: nginx:stable-alpine
#    ports:
#      - "80:80"
#    volumes:
#      - "./nginx.conf:/etc/nginx/nginx.conf"
#    depends_on:
#      - backend
#    networks:
#      - dev

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tasktracker_backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:password@db:5432/tracker
      DEBUG: "False"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
      - ./alembic:/app/alembic
      - ./alembic.ini:/app/alembic.ini
    command: >
      sh -c "
        echo 'Waiting for database...' &&
        alembic upgrade head &&
        echo 'Migrations complete!' &&
        echo 'Starting server...' &&
        uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
      "
    networks:
      - dev

volumes:
  postgres_data: